/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supermercado.view;

import com.supermercado.db.Banco;
import com.supermercado.model.Estoque;
import com.supermercado.model.Produto;
import com.supermercado.model.Refresh;
import com.supermercado.model.Venda;
import java.text.NumberFormat;
import javax.swing.table.DefaultTableModel;

public class JanelaRelatorioVenda extends javax.swing.JFrame implements Refresh{

    /**
     * Creates new form JanelaRelatorio
     */
    public JanelaRelatorioVenda() {
        initComponents();
        //setLocationRelativeTo(null);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCaixa1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCaixa2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCaixa3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        labelTotalCaixa1 = new javax.swing.JLabel();
        labelTotalCaixa2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTotalCaixa3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTotalGeral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Venda");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Relatório de Venda");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/sale.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tbCaixa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCaixa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Subtotal", "Total Recebido", "Troco", "Forma de Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCaixa1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbCaixa1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CAIXA 01:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tbCaixa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCaixa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Subtotal", "Total Recebido", "Troco", "Forma de Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCaixa2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbCaixa2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CAIXA 02:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CAIXA 03:");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        tbCaixa3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCaixa3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Subtotal", "Total Recebido", "Troco", "Forma de Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCaixa3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbCaixa3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("TOTAL:");

        labelTotalCaixa1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotalCaixa1.setText("R$ 0,00");

        labelTotalCaixa2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotalCaixa2.setText("R$ 0,00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TOTAL:");

        labelTotalCaixa3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotalCaixa3.setText("R$ 0,00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("TOTAL:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TOTAL GERAL: ");

        labelTotalGeral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotalGeral.setText("R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalCaixa1)
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalCaixa2)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalGeral)
                                .addGap(148, 148, 148)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalCaixa3)
                                .addGap(60, 60, 60))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelTotalCaixa1))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelTotalCaixa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelTotalCaixa3)
                    .addComponent(jLabel11)
                    .addComponent(labelTotalGeral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotalCaixa1;
    private javax.swing.JLabel labelTotalCaixa2;
    private javax.swing.JLabel labelTotalCaixa3;
    private javax.swing.JLabel labelTotalGeral;
    private javax.swing.JTable tbCaixa1;
    private javax.swing.JTable tbCaixa2;
    private javax.swing.JTable tbCaixa3;
    // End of variables declaration//GEN-END:variables

        // Só funcionará se tiver encerrado uma venda;
        public void atualizarTabela() {
        DefaultTableModel caixa1 = (DefaultTableModel) tbCaixa1.getModel();
        DefaultTableModel caixa2 = (DefaultTableModel) tbCaixa2.getModel();
        DefaultTableModel caixa3 = (DefaultTableModel) tbCaixa3.getModel();
        caixa1.setRowCount(0); // limpando a tabela
        caixa2.setRowCount(0); // limpando a tabela
        caixa3.setRowCount(0); // limpando a tabela
        
        Double totalCaixa1 = 0D;
        Double totalCaixa2 = 0D;
        Double totalCaixa3 = 0D;
        
        for (Venda venda : Banco.vendas) {
            if (venda.getCaixa().equals("01")) {
                Object[] Dados = {venda.getFuncionario().getNome(), NumberFormat.getCurrencyInstance().format(venda.calcularSubtotal()), NumberFormat.getCurrencyInstance().format(venda.getTotalRecebido()), NumberFormat.getCurrencyInstance().format(venda.calcularTroco()), venda.getFormaPagamento()};
                 // adicionando o vetor object[] na tabela com as lista dos produtos salvos.
                 caixa1.addRow(Dados);
                 totalCaixa1 += venda.calcularSubtotal();
            }
       }
        
       for (Venda venda : Banco.vendas) {
            if (venda.getCaixa().equals("02")) {
                Object[] Dados = {venda.getFuncionario().getNome(), NumberFormat.getCurrencyInstance().format(venda.calcularSubtotal()), NumberFormat.getCurrencyInstance().format(venda.getTotalRecebido()), NumberFormat.getCurrencyInstance().format(venda.calcularTroco()), venda.getFormaPagamento()};
                 // adicionando o vetor object[] na tabela com as lista dos produtos salvos.
                 caixa2.addRow(Dados);
                 totalCaixa2 += venda.calcularSubtotal();
            }
       }
       
       for (Venda venda : Banco.vendas) {
            if (venda.getCaixa().equals("03")) {
                Object[] Dados = {venda.getFuncionario().getNome(), NumberFormat.getCurrencyInstance().format(venda.calcularSubtotal()), NumberFormat.getCurrencyInstance().format(venda.getTotalRecebido()), NumberFormat.getCurrencyInstance().format(venda.calcularTroco()), venda.getFormaPagamento()};
                 // adicionando o vetor object[] na tabela com as lista dos produtos salvos.
                 caixa3.addRow(Dados);
                 totalCaixa3 += venda.calcularSubtotal();
            }
       }

       Double totalGeral = totalCaixa1 + totalCaixa2 + totalCaixa3;
       
       labelTotalCaixa1.setText(NumberFormat.getCurrencyInstance().format(totalCaixa1));
       labelTotalCaixa2.setText(NumberFormat.getCurrencyInstance().format(totalCaixa2));
       labelTotalCaixa3.setText(NumberFormat.getCurrencyInstance().format(totalCaixa3));
       labelTotalGeral.setText(NumberFormat.getCurrencyInstance().format(totalGeral));
    }
}
