/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supermercado.view;

import com.supermercado.db.Banco;
import com.supermercado.model.Funcionario;
import javax.swing.JOptionPane;


public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); //centralizar tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btEstoque = new javax.swing.JButton();
        btRelatorioVenda = new javax.swing.JButton();
        btRelatorioEstoque = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btCaixa1 = new javax.swing.JButton();
        btCaixa2 = new javax.swing.JButton();
        btCaixa3 = new javax.swing.JButton();
        btCodigoBarras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Supermercado");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Controle de Supermercado");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/sale.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerencial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btEstoque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/warehouse.png"))); // NOI18N
        btEstoque.setText("Estoque");
        btEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoqueActionPerformed(evt);
            }
        });

        btRelatorioVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRelatorioVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/goods.png"))); // NOI18N
        btRelatorioVenda.setText("Reletório de Vendas");
        btRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioVendaActionPerformed(evt);
            }
        });

        btRelatorioEstoque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRelatorioEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/report.png"))); // NOI18N
        btRelatorioEstoque.setText("Relatório de Estoque");
        btRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRelatorioEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelatorioVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEstoque, btRelatorioEstoque, btRelatorioVenda});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEstoque)
                    .addComponent(btRelatorioVenda)
                    .addComponent(btRelatorioEstoque))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caixas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btCaixa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCaixa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/cashier-machine.png"))); // NOI18N
        btCaixa1.setText("Caixa 1");
        btCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixa1ActionPerformed(evt);
            }
        });

        btCaixa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCaixa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/cashier-machine.png"))); // NOI18N
        btCaixa2.setText("Caixa 2");
        btCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixa2ActionPerformed(evt);
            }
        });

        btCaixa3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCaixa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/cashier-machine.png"))); // NOI18N
        btCaixa3.setText("Caixa 3");
        btCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixa3ActionPerformed(evt);
            }
        });

        btCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCodigoBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/supermercado/resource/bar-code-scanner.png"))); // NOI18N
        btCodigoBarras.setText("Leitor de Código de Barras");
        btCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCodigoBarrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCaixa2)
                .addGap(18, 18, 18)
                .addComponent(btCaixa3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCaixa1, btCaixa2, btCaixa3});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCaixa1)
                    .addComponent(btCaixa2)
                    .addComponent(btCaixa3))
                .addGap(18, 18, 18)
                .addComponent(btCodigoBarras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCaixa2, btCodigoBarras});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixa1ActionPerformed
        JanelaCaixa caixa = new JanelaCaixa("01");
        caixa.setVisible(true);
    }//GEN-LAST:event_btCaixa1ActionPerformed

    private void btCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixa2ActionPerformed
        JanelaCaixa caixa = new JanelaCaixa("02");
        caixa.setVisible(true);
    }//GEN-LAST:event_btCaixa2ActionPerformed

    private void btCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixa3ActionPerformed
        JanelaCaixa caixa = new JanelaCaixa("03");
        caixa.setVisible(true);
    }//GEN-LAST:event_btCaixa3ActionPerformed

    private void btEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoqueActionPerformed
        if (this.isLoginGerente()) {
            JanelaEstoque estoque = new JanelaEstoque();
            estoque.setVisible(true);
        }
    }//GEN-LAST:event_btEstoqueActionPerformed

    private void btRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioEstoqueActionPerformed
        if (this.isLoginGerente()) {
            JanelaRelatorioEstoque relatorio = new JanelaRelatorioEstoque();
            relatorio.setVisible(true);
        }
    }//GEN-LAST:event_btRelatorioEstoqueActionPerformed

    private void btRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioVendaActionPerformed
        if (this.isLoginGerente()) {
            JanelaRelatorioVenda relatorio = new JanelaRelatorioVenda();
            relatorio.setVisible(true);
        }
    }//GEN-LAST:event_btRelatorioVendaActionPerformed

    private void btCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCodigoBarrasActionPerformed
        JanelaLeitor leitor = new JanelaLeitor();
        leitor.setVisible(true);
    }//GEN-LAST:event_btCodigoBarrasActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Banco.iniciar();
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCaixa1;
    private javax.swing.JButton btCaixa2;
    private javax.swing.JButton btCaixa3;
    private javax.swing.JButton btCodigoBarras;
    private javax.swing.JButton btEstoque;
    private javax.swing.JButton btRelatorioEstoque;
    private javax.swing.JButton btRelatorioVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    
    public boolean isLoginGerente() {
        JanelaLogin janelaLogin = new JanelaLogin(this, true);
        janelaLogin.setVisible(true);
        
        Funcionario funcionarioLogado = janelaLogin.getFuncionarioLogado();
        if (funcionarioLogado == null) {
            JOptionPane.showMessageDialog(null, "Usuário/senha incorretos", "Acesso negado", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!funcionarioLogado.getIsGerente()) {
            JOptionPane.showMessageDialog(null, "Somente o gerente pode ter acesso", "Acesso negado", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
}
